name: release-please

on:
  push:
    branches:
      - main
      - "[0-9].[0-9].[0-9]"

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          default-branch: "${{ github.ref }}"

